security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        chain_provider:
           chain:
               providers: [fos_userbundle, my_fos_facebook_provider]

        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
        my_fos_facebook_provider:
            id: my.facebook.user

        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            fos_facebook:
                provider: my_fos_facebook_provider
                redirect_to_facebook_login: false
                login_path: /user/login
                check_path: /facebook/login_check

            logout:
                path: /facebook/logout
            anonymous: ~


    access_control:
         - { path: /.*, roles: [ROLE_USER, IS_AUTHENTICATED_ANONYMOUSLY] }
