# src/VoteCerto/WebBundle/Resources/config/doctrine/Vote.mongodb.yml
VoteCerto\WebBundle\Document\Comments:
    fields:
        id:
            id: true
        vote:
            type: boolean
        comment:
            type: string
        facebookId:
            type: string
        facebookName:
            type: string

    type: document
    referenceOne:
        parliamentarian:
            targetDocument: Parliamentarian