# src/VoteCerto/WebBundle/Resources/config/doctrine/Parliamentarian.mongodb.yml
VoteCerto\WebBundle\Document\Parliamentarian:
    fields:
        id:
            id: true
        idParliamentarian:
            type: int
        condition:
            type: string
        registration:
            type: int
        name:
            type: string
        fantasyName:
            type: string
        photo:
            type: string
        sex:
            type: string
        state:
            type: string
        filiation:
            type: string
        cabinet:
            type: string
        attachment:
            type: string
        phone:
            type: string
        email:
            type: string
        localizer:
            type: int
        votes:
            type: int
        slug:
            type: string
        committees:
            type: collection

    type: document
    referenceMany:
        comments:
            targetDocument: Comments