# src/VoteCerto/WebBundle/Resources/config/doctrine/Vote.mongodb.yml
VoteCerto\WebBundle\Document\Vote:
    fields:
        id:
            id: true
        vote:
            type: boolean
        comment:
            type: string

    type: document
    referenceOne:
        parliamentarian:
            targetDocument: Parliamentarian