web_homepage:
    pattern:  /
    defaults: { _controller: WebBundle:Default:index }

webbundle_profile:
    pattern:  /parlamentar/{slug}
    defaults: { _controller: WebBundle:Profile:index }

vote:
    pattern: /parlamentar/{slug}/vote
    defaults: { _controller: WebBundle:Profile:vote }